using Orchard.ContentManagement.MetaData;
using Orchard.Core.Contents.Extensions;
using Orchard.Data.Migration;
using Orchard.Environment.Extensions;

// This code was generated by Orchardizer
namespace Hazza.Blogging
{
	[OrchardFeature("Hazza.Blogging.ContainerCommentCount")]
    public class ContainerCommentsMigrations : DataMigrationImpl {
            public int Create() {
            ContentDefinitionManager.AlterPartDefinition("ContainerCommentsCountPart", builder => builder
                .Attachable()
                .WithDescription("Attach to containers to display a total comments count for all contained items")
            );


            return 1;
        }
    }
}
