using Orchard.ContentManagement;
using Orchard.Environment.Extensions;

// This code was generated by Orchardizer
namespace Hazza.Blogging.Models
{
    [OrchardFeature("Hazza.Blogging.ContainerCommentCount")]
    public class ContainerCommentsCountPart : ContentPart {
        public int Count {
            get { return this.Retrieve(x => x.Count); }
            set { this.Store(x => x.Count, value); }
        }

        public int PendingCount {
            get { return this.Retrieve(x => x.PendingCount); }
            set { this.Store(x => x.PendingCount, value); }
        }
    }
}